### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rapier1** [provider-corner/vigenere#3]
I'm in the process of trying to convert a cipher that was built in OSSL 1.1.1 by using the meth_new process (it's a multithreaded aes ctr cipher used in hpnssh). I obviously need to move this over to a provider. However, the documentation (at least that provided by OpenSSL) is a bit... almost useful but not quite. Is there a resource that you know of that can help? I've just got a lot of questions that are, likely, basic. I'm sorry for the random ask but I'm hitting a lot of walls right now and I'm really hoping there is a decent resource you could point me towards. 

Thanks, 

Chris

**Comment by levitte** [comment]
Providers are fairly new, so if you're looking for something more like a tutorial, there isn't so much... yet.

Fact is, this vigenere project is meant to be a sort of tutorial in code.  I'm sure it could use a lot more commentary to be easier to understand, and I'm perfectly willing to do so, if I know what needs answering.

Being one of the architects behind the provider functionality, I'm certain to see things as self-evident where that may be the case. I'll gladly take all questions I get and will answer as time permits.

(Perhaps I should open up a discussion tab somewhere in provider-corner...)

**Comment by levitte** [comment]
In other words, feel free to ask, just be patient with my time.

**Comment by levitte** [comment]
I also just enabled the discussions tab, you'll find it here: https://github.com/orgs/provider-corner/discussions
Feel free to try it as well.

**Comment by levitte** [comment]
Closing this, since the discussion continued [here](https://github.com/orgs/provider-corner/discussions/2)
