### ISSUE TITLE
Key length bug

### ISSUE THREAD

**Issue by mattcaswell** [provider-corner/vigenere#4]
It looks to me (from code inspection) that `vigenere_encrypt_init`/`vigenere_decrypt_init` will happily accept a 0 length key. In the encrypt case it will end up calling memcpy with a final param of 0 (which I think is undefined behaviour). `vigenere_update` will subsequently result in an out-of-bounds or NULL pointer deref of the zero length key (because it assumes that the key is at least one byte long).

**Comment by levitte** [comment]
The undefined behavior is rather that `malloc()` may or may not return NULL, and `memcpy()` to NULL is a no-no, right?

**Comment by mattcaswell** [comment]
Yeah, that's probably right.

**Comment by levitte** [comment]
I believe that 06b721b9ba5b957aa011ca92a7232bf0b349c3d1 fixes that

**Comment by mattcaswell** [comment]
LGTM
